
version: "3.7"

services:
  mongo:
    image: mongo:4.0.4
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - internal
  web:
    build: ./web-api/
    command: npm run dev
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./web-api/:/app/
      - /app/node_modules
    networks:
      - internal

networks:
  internal:

volumes:
  web-api:
  data: