
version: "3.3"

services:
  mongo:
    image: mongo:4.2.1-bionic
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./web-api/:/usr/src